[build-system]
requires = ["setuptools", ]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
dependencies = [
    "scikit-image",
    "scikit-spatial",
    "opencv-python",
    "numpy",
    "matplotlib",
]